// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhnpFlQ7nLzjflOdFEp4B-W4P5Z3htpl0',
    appId: '1:496803122868:web:bd22e373ae3a0f364e51e1',
    messagingSenderId: '496803122868',
    projectId: 'ridepool-8bac6',
    authDomain: 'ridepool-8bac6.firebaseapp.com',
    storageBucket: 'ridepool-8bac6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoLTlHLseqlASmiQm4Q1QqeHUbCQeBCug',
    appId: '1:496803122868:android:6ab80b4d4ef310c64e51e1',
    messagingSenderId: '496803122868',
    projectId: 'ridepool-8bac6',
    storageBucket: 'ridepool-8bac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDP3tcdi6HrYivg8i5IpE7BcuF0Od0qwc',
    appId: '1:496803122868:ios:20f155cc6d952b204e51e1',
    messagingSenderId: '496803122868',
    projectId: 'ridepool-8bac6',
    storageBucket: 'ridepool-8bac6.firebasestorage.app',
    iosClientId: '496803122868-st5i497ovir6vm1i1equp56da62em7s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridepool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDP3tcdi6HrYivg8i5IpE7BcuF0Od0qwc',
    appId: '1:496803122868:ios:20f155cc6d952b204e51e1',
    messagingSenderId: '496803122868',
    projectId: 'ridepool-8bac6',
    storageBucket: 'ridepool-8bac6.firebasestorage.app',
    iosClientId: '496803122868-st5i497ovir6vm1i1equp56da62em7s3.apps.googleusercontent.com',
    iosBundleId: 'com.example.ridepool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhnpFlQ7nLzjflOdFEp4B-W4P5Z3htpl0',
    appId: '1:496803122868:web:3f62aa5bc70a57374e51e1',
    messagingSenderId: '496803122868',
    projectId: 'ridepool-8bac6',
    authDomain: 'ridepool-8bac6.firebaseapp.com',
    storageBucket: 'ridepool-8bac6.firebasestorage.app',
  );

}